config/routes.rb
BillSplitr::Application.routes.draw do
  root to: 'static_pages#home'

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:index, :show] do
      collection do 
        get :friends 
      end
    end
    resources :bills, only: [:index, :create, :show]
    resources :bill_shares, only: [:index, :create, :update]
    resources :friendships, only: [:create]

    get '/dashboard', to: 'users#balances'
    post '/update_balance', to: 'bill_shares#batch_update'
  end
end

app/views/layouts/_errors.html.erb
<div class="alert alert-danger">
  <ul>
    <% flash[:errors].each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse">

  <div class="navbar-header">
    <%= link_to "BillSplitr", '#', class: 'navbar-brand' %>
    <button type="button"
            class="navbar-toggle"
            data-toggle="collapse"
            data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>

  <div class="navbar-responsive-collapse navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-left">
      <li>
        <%= link_to '+ New Bill','/#/bills/new' %>
      </li>
      <li>
        <%= link_to '+ Add Friends', '/#/friends' %>
      </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <%= "#{current_user.f_name} #{current_user.l_name}" %>
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to "Log Out", session_url, method: :delete %>
          </li>
        </ul>
      </li> <!-- dropdown -->
    </ul>

  </div>
</div>

app/views/layouts/_notice.html.erb
<div class="alert alert-success">
  <%= flash[:notice] %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BillSplitr</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
<% if logged_in? %>
  <%= render 'layouts/navbar' %>
<% end %>
<div class="container">
  <%= yield %>
</div>
</body>
</html>